version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - type: bind
        source: .
        target: /var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=db_irroba
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_irroba
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: .
        target: /var/www
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql_data:
    driver: local